# name of the log group to use. If it doesn't exist, will try to create it first
# default value is: ros_log_group
log_group_name: person_detection_example

# name of the log stream to send logs to. If it doesn't exist, will try to create it first
# default value is: ros_log_stream
log_stream_name: Turtlebot3

# how often to send a batch of logs to cloudwatch in the log group and log stream specified
# default value is: 5.0
publish_frequency: 5.0

# whether to subscribe to the rosout_agg topic to get logs
# default value is: true
sub_to_rosout: true

# other topics to subscribe to get logs
# default value is: empty list
topics: []

#aws region configuration
aws_client_configuration:
  region: "us-west-2"
  connect_timeout_ms: 9000
  request_timeout_ms: 9000
