kinesis_video_streamer:
  ros__parameters:
    aws_client_configuration:
      # Specifies where you want the client to communicate. Examples include us-east-1 or us-west-2.
      region: "us-west-2"

      # Values that determine the length of time, in milliseconds, to wait before timing out a request. 
      connect_timeout_ms: 9000
      request_timeout_ms: 9000
      # The maximum number of allowed connections to a single server for your HTTP communications. The default value is 25.
      # You can set this value as high as you can support the bandwidth. We recommend a value around 25.
      #maxConnections: 25

      # The number of retries for connecting to AWS Services
      max_retries: 10

    kinesis_video:
      stream_count: 1
      stream0:
        # Kinesis Video Stream name. If a stream by the given name doesn't exist, it will be created.
        stream_name: "RoboMakerPersonDetectionVideoStream"

        # Topic name to subscribe and receive the image/video data from.
        subscription_topic: /video/encoded

        # Topic type
        # 1: KinesisVideoFrame transport, enabling h264 streaming
        # 2: sensor_msgs::Image transport.
        # 3: Like 1 but with AWS Rekognition support built-in. Results will be read from 'rekognition_data_stream' and published onto 'rekognition_topic_name'.
        topic_type: 3

        #### If topic_type is 3, we expect the following parameters.
        ### The Kinesis Data Stream from which to read Rekognition's analysis results.
        rekognition_data_stream: "AmazonRekognitionPersonDetectionStream"
        ### The ROS topic on which to publish the results.
        rekognition_topic_name: "/rekognition/results"

        # Frame rate should match the encoder's (and the camera's) frame rate.
        frame_rate: 30

        # Rather than using the input's timestamps, let the Producer SDK create timestamps as the frames arrive.
        frame_timecodes: false
